openapi: 3.0.1
info:
  title: AggregatorAPI
  description: API Definition of AggregatorAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/aggregator
paths:
  /:
    get:
      responses:
        default:
          description: Default response
